cc_library(
    name = "matrix_lib",
    srcs = [
    ],
    hdrs = [
        "matrix.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)

cc_test(
    name = "matrix_test",
    srcs = [
        "matrix_test.cc",
    ],
    deps = [
        ":matrix_lib",
        "//util:util_lib",
    ],
)
